exclude: 'migrations|.git|.tox'
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language: system

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/prospector
    rev: 1.2.0
    hooks:
      - id: prospector
        language: system

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.0.1
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
